name = "caneva20's Create 1.19 [Forge]"
author = "caneva20"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2672375cba4af451e78dc55fbff48f6f02c24dfe84f5fb232aef95e018703a9b"

[versions]
forge = "43.2.10"
minecraft = "1.19.2"
