name = "caneva20's Create 1.19 [Forge]"
author = "caneva20"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5a2e9e85a82f0800f3638f2abe2cf3039c602cb748ce559c649178e66e7db500"

[versions]
forge = "43.2.10"
minecraft = "1.19.2"
