name = "caneva20's Create 1.19 [Forge]"
author = "caneva20"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "42d5dd72a1577f79dd6a03bcf438433e86c7fd02b438ebff957510e459abc030"

[versions]
forge = "43.2.10"
minecraft = "1.19.2"
