name = "caneva20's Create 1.19 [Forge]"
author = "caneva20"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1a0019556a72edb56138163858ac5a520b0b10447e9b00c2487d0a7ed3051a42"

[versions]
forge = "43.2.10"
minecraft = "1.19.2"
