name = "caneva20's Create 1.19 [Forge]"
author = "caneva20"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "55545b9467757464b3d05d1c67dcb98e3f76589bb2b89121da86bec778944885"

[versions]
forge = "43.2.10"
minecraft = "1.19.2"
