name = "caneva20's Create 1.19 [Forge]"
author = "caneva20"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b546c991f6ee05267c014e563737ad734b83350a4a98fac0307a80e48539ff5e"

[versions]
forge = "43.2.10"
minecraft = "1.19.2"
