name = "caneva20's Create 1.19 [Forge]"
author = "caneva20"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "84282043972d5e5bada70a12fc7e1556088ee9f1a260ec4b1db7f0e09c8aa4a8"

[versions]
forge = "43.2.10"
minecraft = "1.19.2"
